### ISSUE TITLE
Enable block level links 

### ISSUE THREAD

**Issue by apawlik** [stencila/website#19]
Just like they are available through Discuss 
![image](https://user-images.githubusercontent.com/2358535/39669843-c1700b00-514b-11e8-9d35-1a9994c9d9e3.png)

**Comment by nokome** [comment]
I suggest that we perhaps generalise this into a `related` posts item in the YAML front matter which generates these 'cards' with link, images and abstract at the end, or in the side bar, of each post. Is that what you envisaged @apawlik

**Comment by apawlik** [comment]
Precisely! I didn't know what to google out (`related`!) Will try it out and see what happens.

**Comment by nokome** [comment]
I don't think that googling will help much here - just because we're implementing our own font matter handling in our templates.  So we can add whatever tag we want `related` or `suggested` or whatever. Just as long as we have something in the templates that handle it. Sounds complicated but it's not - I'll quickly create a PR to illustrate - I think it will be a useful exercise to illustrate how we can extend and use the front matter for other places in the site.

**Comment by apawlik** [comment]
I see! OK. I get it (I think). I'll give it a short go.

**Comment by nokome** [comment]
I did a quick iteration on this mainly just to illustrate how how this sort of extension can be acheived:

In a blog post YAML header you can now add a `suggested` item:

```
suggested:
    - ../introducing-sheets
    - ../underneath-sheets
```

which gets rendered as:

![image](https://user-images.githubusercontent.com/1152336/39733779-720bf8fc-52c8-11e8-8fc6-363ca6c84f78.png)

by this bit of [Nunjucks template](https://github.com/stencila/website/blob/4f6be9308bc978c3a0e852d3ee231508b4c63f02/src/blog/_post.html#L11)

Note that the `suggested` list is getting pre-processed [here](https://github.com/stencila/website/blob/4f6be9308bc978c3a0e852d3ee231508b4c63f02/gulpfile.js#L37) to get image and title etc. Sometime we could add defaults for suggested - the last 3 posts for example.
